package com.darien.openweathertest.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.darien.openweathertest.db.Zip;

import com.darien.openweathertest.db.ZipDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zipDaoConfig;

    private final ZipDao zipDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zipDaoConfig = daoConfigMap.get(ZipDao.class).clone();
        zipDaoConfig.initIdentityScope(type);

        zipDao = new ZipDao(zipDaoConfig, this);

        registerDao(Zip.class, zipDao);
    }
    
    public void clear() {
        zipDaoConfig.getIdentityScope().clear();
    }

    public ZipDao getZipDao() {
        return zipDao;
    }

}
